version: 2

defaults: &defaults
  docker:
    - image: circleci/php:5.6
  working_directory: ~/project

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: composer require phplint
          command: composer global require overtrue/phplint
      - run:
          name: run phplint
          command: ~/.composer/vendor/bin/phplint --exclude vendor .
  build:
    <<: *defaults
    steps:
      - checkout

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build
